version: '3.3'

services:
  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"

  local:
    build: .
    command: /app/local.sh
    ports:
      - 4000
    environment: &ENV
      VIRTUAL_HOST: api.local.dockito.org
      VIRTUAL_PORT: 4000
      DB_PASSWORD: password
      DB_NAME: eventful_dev
      DB_HOST: db
    volumes:
        - ./:/app
    links:
      - db
    depends_on:
      - db

  test:
    build: .
    command: /app/test.sh
    environment:
      DB_PASSWORD: password
      DB_NAME: eventful_test
      DB_HOST: db
    volumes:
        - ./:/app
    links:
      - db
    depends_on:
      - db