version: '3.3'

services:
  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"

<<<<<<< HEAD
  local:
=======
  web:
>>>>>>> 2c20431b5ae48766f05cfacc18c9b9016b400d73
    build: .
    command: /app/local.sh
    ports:
      - 4000
    environment: &ENV
      DB_PASSWORD: password
      DB_NAME: eventful_dev
      DB_HOST: db
      MIX_ENV: dev
    volumes:
        - ./:/app
    links:
      - db
    depends_on:
<<<<<<< HEAD
      - db

  test:
    build: .
    command: /app/test.sh
    environment:
      DB_PASSWORD: password
      DB_NAME: eventful_test
      DB_HOST: db
      MIX_ENV: test
    volumes:
        - ./:/app
    links:
      - db
    depends_on:
=======
>>>>>>> 2c20431b5ae48766f05cfacc18c9b9016b400d73
      - db