version: '3.3'

services:
  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"

  redis:
    image: redis

  web:
    build: .
    command: /app/local.sh
    ports:
      - 4000
    environment: &ENV
      DB_PASSWORD: password
      DB_NAME: eventful_dev
      DB_HOST: db
      MIX_ENV: dev
      REDIS_URL: redis
    volumes:
        - ./:/app
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
